### ISSUE TITLE
Submit page

### ISSUE THREAD

**Issue by johav** [AfricArxiv/africarxiv.github.io#21]
how about we give the embedded OSF AfricArxiv uploading page its own tab on our Github website?
That way ppl have all information in one place and don't have to leave Africarxiv.github.io which can be renamed into africarxiv.org

**Comment by johav** [comment]
- [ ] rename from "Submission Guidelines" to "Submit"
- [ ] embedd OSF submission website/interface (full window width): https://osf.io/preprints/africarxiv/submit
- [ ] underneath add [submission guidelines 2019](https://github.com/AfricArxiv/africarxiv.github.io/blob/master/Submission%20Guidelines%202019.docx) as text

**Comment by samuell** [comment]
>  embed OSF submit a paper page (full window width)

I just tried implementing this locally, to URL https://osf.io/preprints/africarxiv/submit but it turns out this page redirects to a login page for OSF that does not allow being opened from an iframe (for security reasons I suppose):

![Selection_999(148)](https://user-images.githubusercontent.com/125003/54476835-f5f2ad80-4801-11e9-8b46-faab468289a0.png)

**Comment by samuell** [comment]
@johav But anyways, I guess this issue is no longer relevant now with the new wordpress site going online soon, right?

**Comment by johav** [comment]
exactly, but thanks for checking :)
We wanted to do the same on wordpress - doesn't seem to work. Nevermind, we can redirect to OSF.
